[package]
name = "http-counter"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
hyper = "0.13.0-alpha.4"
tokio = "0.2.0-alpha.6"
jemallocator = "0.3"

[profile.release]
lto = true
